# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
name: Go
on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Create SQL database test
        run: go test -v ./tests/data/CreateSQL_test.go
      - name: Load data test
        run: go test -v ./tests/data/load_test.go
      - name: Add functions test
        run: go test -v ./tests/data/add_test.go
      - name: Edit data test
        run: go test -v ./tests/data/edit_test.go
      - name: delete records test
        run: go test -v ./tests/data/deleteRecord_test.go
      - name: delete general test
        run: go test -v ./tests/data/delete_test.go
