# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

 Test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Create SQL database test
      run: go test -v ./data/tests/CreateSQL_test.go

    - name: Load data test
      run: go test -v ./data/tests/load_test.go 
    
    - name: Add functions test
      run: go test -v ./data/tests/add_test.go
    - name: Edit data test
      run: go test -v ./data/tests/edit_test.go
    - name: delete records test
      run: go test -v ./data/tests/deleteRecord_test.go
    - name: delete general test
      run: go test -v ./data/tests/delete_test.go
    
    
